import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "@/assets/styles/global.scss";
import React, { ReactNode } from "react";
import { i18n } from "../../../i18nConfig";
import NextAuthSessionProvider from "../../core/layouts/NextAuthSessionProvider";
import { ThemeProvider } from "@mui/system";
import { theme } from "@/theme/theme";
import CustomThemeProvider from "@/theme/CustomThemeProvider";

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) => {
  return (
    <html lang={locale}>
      <body className={kanit.className}>
        <NextAuthSessionProvider>
          <CustomThemeProvider>{children}</CustomThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
